### ISSUE TITLE
Quarantine Host reaction

### ISSUE THREAD

**Issue by Link009** [mohlcyber/MAR-Automation-Script#1]
Hi @mohlcyber

I see from the documentation that the arguments section of QuarantineHosts is missing: [QuarantineHosts section](https://docs.mcafee.com/bundle/active-response-2.4.0-product-guide/page/GUID-F4ACAED9-8E60-47E3-B6AF-782974598352.html).

I expected that an argument like hostname (at least) was required.

Can you please give that information here and, eventually, review the documentation ? 

Thanks

**Comment by mohlcyber** [comment]
Hi @Link009 

thats right. If you want to quarantine a host there is no reaction argument required. They payload to quarantine a host would look like this:

{"queryId":"2434","resultIds":["{1=[SER2]}"],"reactionId":"22","reactionArguments":{}}

Basically you need to run a search to retrieve the query id and the resultId's. You will also need the reactionId for the quarantinehost reaction. Based on the resultId we know which host to quarantine.

I can post a sample python script if required. 
If you have any questions or need further details please let me know.

All the best,
Martin

**Comment by mohlcyber** [comment]
I will close the issue for now. Please reopen if you have any questions.
All the best,
Martin
